### PR TITLE
Improved functionality and documentation to DiseasySeason

### LINKED ISSUE #25: DiseasySeason: Implement a get_season_model
DiseasySeason presently works by setting the internal `$model_t()` and `$model_date()` through `$use_season_*` methods.

It is requested that set of `$get_season_*` functions be implemented that can return the functions without setting the internal methods.
These `$get_season_*` methods can then be called by the `$use_season_*`functions and set the internal methods.

### LINKED ISSUE #40: DiseasySeason: Add vignette that describes basic principles
The `DiseasySeason` is a central module that should have its own vignette describing the basic principles.

See our [documentation standard](https://github.com/ssi-dk/diseasy/wiki/Diseasy-documentation-standard#super-documentation) for details

### PR DESCRIPTION
**Pull request by RasmusSkytte**
### Intent
This PR aims to do a number of fixes to the DIseasySeason module.
1) It implements the `get_*` versions of the current `use_*` functions (fixes #25)
2) It adds a vignette describing the use of the module (fixes #40)
2a) For this, the PR also introduces the convenience active binding `$available_season_models`
3) It documents the @description of the module (fixing parts of #37)

### Approach
For `get_*` and `use_*` functions, the previous `use_*` functions are split into two.
The first part of the functions is transferred to the new `get_*` functions while the last parts are kept in the
new `use_*` functions. These new `use_*` functions in-turn call the corresponding `get_*` functions to retain 
their function.

### Known issues
* [x] PR #53 needs to be merged before test will work (there is a issue with `printr` that this PR fixes)

### Checklist

* [x] The PR passes all local unit tests
* [ ] I have documented any new features introduced
* [ ] If the PR adds a new feature, please add an entry in `NEWS.md`
* [x] A reviewer is assigned to this PR

### CODE REVIEW

**Comment by RasmusSkytte** [comment]
Rebasing onto the updated main and removing some changes.

**Review by telkamp7 — COMMENTED** [review]
Obviously, there seems to be a problem in the `$describe` method, which fails to evaluate in line 38 in the disease-season.Rmd file. I do not know enough about the codebase to resolve the issue, but when I try to execute the commands locally, I get a "directoryError".

**Comment by telkamp7** [comment]
I dug a little deeper, and identified that you have defined your own `printr()` function. I see that this function is the root-cause of the failing check. 

When the `$describe` method is executed, it calls your `printr()` function. The error you're encountering is due to the use of the `sink()` function within your `printr()` function. The sink function is used to divert R output to a file, and it's causing the error because it's trying to open a file at the path "/dev/null," which doesn't exist in many environments.

**Comment by RasmusSkytte** [comment]
> I dug a little deeper, and identified that you have defined your own `printr()` function. I see that this function is the root-cause of the failing check.
> 
> When the `$describe` method is executed, it calls your `printr()` function. The error you're encountering is due to the use of the `sink()` function within your `printr()` function. The sink function is used to divert R output to a file, and it's causing the error because it's trying to open a file at the path "/dev/null," which doesn't exist in many environments.

Yes, you are right that this is the reason that it is currently failing on windows back-ends. PR #53 has a fix for this issue since it is a separate issue (not related to `DiseasySeason`). Once that PR is merged, the checks will succeed.

**Review by telkamp7 — APPROVED** [review]
As #53 have been fixed, I can now approve these changes!

**Pull request merged**
